workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - slaeat
      ios_signing:
        distribution_type: app_store
        bundle_identifier: jp.nicchizu.slaeat
    scripts:
      - name: Create secrets.dart
        script: |
          echo "const String hotpepperApiKey = '$HOTPEPPER_API_KEY';" > lib/secrets.dart
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Generate ExportOptions.plist
        script: |
          cat > /tmp/ExportOptions.plist <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>app-store</string>
    <key>signingStyle</key>
    <string>manual</string>
    <key>provisioningProfiles</key>
    <dict>
        <key>jp.nicchizu.slaeat</key>
        <string>SLAEAT AppStore</string>
    </dict>
</dict>
</plist>
PLIST
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/tmp/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - mt166431@gmail.com
